### ISSUE TITLE
Issue when clearing selected option with type 'tag'

### ISSUE THREAD

**Issue by parthpatel108** [pcbowers/sanity-plugin-tags#10]
`    const tempTag: GeneralTag = {
      ...tag,
      label: tag._label_temp,
      value: tag._value_temp,
    }
`

 I am using sanity-plugin-tags and implement a dropdown with` isClearable : true`  in my schema , problem is that when I am clearing the dropdown sanity studio notify some error
 
 
![image](https://user-images.githubusercontent.com/37935367/173775067-06427753-dc9d-4d13-a443-0c856d24b085.png)

**Comment by pcbowers** [comment]
@parthpatel108 The `isClearable` option needs to be specified through the `reactSelectOptions` which is currently a 'use-at-your-own-risk' property. I originally was not going to provide this option, but decided to in a limited fashion in the off chance that it would be useful to someone if it does work. However, the scope of react-select is pretty large and providing support for all of its properties is outside the scope of this plugin. I am labeling this as `wontfix`, but if you want to tackle this yourself and submit a pull request, feel free!

**Comment by parthpatel108** [comment]
@pcbowers okay, thanks for your information 🤗👍
