### ISSUE TITLE
Styled-components v6.x needed for Studio v3.36.x to run

### ISSUE THREAD

**Issue by WebShapedBiz** [pcbowers/sanity-plugin-tags#31]
Hi.
With new Studio v3.36.x there is no more option to run this plugin with Styled Components v5.x. The studio just won't start. Here is the explanation from the latest release:

If you encounter an error such as TypeError: Cannot read properties of undefined (reading 'div'), please make sure your Studio doesn't depend on styled-components@5. Updating any such dependencies to styled-components@6 should resolve the error.
This error is caused by an ESM/CJS compability issue in @sanity/ui.

Is there a chance we could see the update for this plugin addressing this issue?

Cheers.

**Comment by Myriade** [comment]
Hi. Same request. I need to install tags plugin on a new Sanity project, that uses Styled-component v6.x.

Thank you.

**Comment by dariomac** [comment]
Same here! I can't upgrade Sanity to 3.38.0 because of this.

**Comment by pcbowers** [comment]
Fixed with #26
